package models

func (l EnglishUnitedKingdom) State() []string {
	return []string{
		"Aberdeenshire",
		"Anglesey",
		"Angus (Forfarshire)",
		"Antrim",
		"Argyllshire",
		"Armagh",
		"Ayrshire",
		"Banffshire",
		"Bedfordshire",
		"Berkshire",
		"Berwickshire",
		"Breconshire",
		"Buckinghamshire",
		"Buteshire",
		"Caernarvonshire",
		"Caithness",
		"Cambridgeshire",
		"Cardiganshire",
		"Carmarthenshire",
		"Cheshire",
		"Clackmannanshire",
		"Cornwall",
		"Cumbria",
		"Denbighshire",
		"Derbyshire",
		"Derry",
		"Devon",
		"Dorset",
		"Down",
		"Dumfries-shire",
		"Dunbartonshire",
		"Durham",
		"E. Riding of Yorkshire",
		"East Lothian",
		"East Sussex",
		"Essex",
		"Fermanagh",
		"Fife",
		"Flintshire",
		"Glamorgan",
		"Gloucestershire",
		"Greater London",
		"Greater Manchester",
		"Hampshire",
		"Herefordshire",
		"Hertfordshire",
		"Inverness-shire",
		"Kent",
		"Kincardineshire",
		"Kinross-shire",
		"Kirkcudbrightshire",
		"Lanarkshire",
		"Lancashire",
		"Leicestershire",
		"Lincolnshire",
		"Londonderry",
		"Merionethshire",
		"Merseyside",
		"Midlothian",
		"Monmouthshire",
		"Montgomeryshire",
		"Morayshire",
		"Nairnshire",
		"Norfolk",
		"North Yorkshire",
		"Northamptonshire",
		"Northumberland",
		"Nottinghamshire",
		"Orkney Islands",
		"Oxfordshire",
		"Peebles-shire",
		"Pembrokeshire",
		"Perthshire",
		"Radnorshire",
		"Renfrewshire",
		"Ross & Cromarty",
		"Roxburghshire",
		"Rutland",
		"S. Yorkshire",
		"Selkirkshire",
		"Shetland Islands",
		"Shropshire",
		"Somerset",
		"Staffordshire",
		"Stirlingshire",
		"Suffolk",
		"Surrey",
		"Sutherland",
		"Tyne & Wear",
		"Tyrone",
		"W. Yorkshire",
		"Warwickshire",
		"West Lothian",
		"West Midlands",
		"West Sussex",
		"Wigtownshire",
		"Wiltshire",
		"Worcestershire",
	}
}
